apiVersion: v1
kind: Secret
metadata:
  name: {{ include "algorycode-rent-service.fullname" . }}-secret
  labels:
    {{- include "algorycode-rent-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.secret.data.springDatasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.data.springDatasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.data.springDatasourcePassword | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.secret.data.springRabbitmqUsername | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secret.data.springRabbitmqPassword | quote }}
