apiVersion: v1
kind: Secret
metadata:
  name: {{ include "algorycode-rent-service.fullname" . }}-secret
  labels:
    {{- include "algorycode-rent-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_RABBITMQ_USERNAME: {{ .Values.secret.data.springRabbitmqUsername | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secret.data.springRabbitmqPassword | quote }}
  APP_OBJECT_STORAGE_ACCESS_KEY: {{ .Values.secret.data.appObjectStorageAccessKey | quote }}
  APP_OBJECT_STORAGE_SECRET_KEY: {{ .Values.secret.data.appObjectStorageSecretKey | quote }}
