CREATE TABLE IF NOT EXISTS vehicle_fuel_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  label_tr VARCHAR(128) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT uq_vehicle_fuel_types_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS vehicle_transmission_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  label_tr VARCHAR(128) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT uq_vehicle_transmission_types_code UNIQUE (code)
);

INSERT INTO vehicle_fuel_types (code, label_tr, sort_order) VALUES
  ('benzin', 'Benzin', 10),
  ('dizel', 'Dizel', 20),
  ('hibrit', 'Hibrit', 30),
  ('elektrik', 'Elektrik', 40)
ON CONFLICT (code) DO UPDATE SET
  label_tr = EXCLUDED.label_tr,
  sort_order = EXCLUDED.sort_order;

INSERT INTO vehicle_transmission_types (code, label_tr, sort_order) VALUES
  ('otomatik', 'Otomatik', 10),
  ('manuel', 'Manuel', 20)
ON CONFLICT (code) DO UPDATE SET
  label_tr = EXCLUDED.label_tr,
  sort_order = EXCLUDED.sort_order;
