CREATE TABLE IF NOT EXISTS vehicle_allowed_return_handovers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  vehicle_id BIGINT NOT NULL,
  handover_location_id BIGINT NOT NULL,
  line_order INT NOT NULL DEFAULT 0,
  CONSTRAINT uk_vehicle_allowed_return_vehicle_handover UNIQUE (vehicle_id, handover_location_id)
);

CREATE INDEX IF NOT EXISTS idx_varh_vehicle_id ON vehicle_allowed_return_handovers (vehicle_id);

DO $migration$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'vehicles'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_varh_vehicle'
  ) THEN
    ALTER TABLE vehicle_allowed_return_handovers
      ADD CONSTRAINT fk_varh_vehicle
      FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE;
  END IF;
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'handover_locations'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_varh_handover'
  ) THEN
    ALTER TABLE vehicle_allowed_return_handovers
      ADD CONSTRAINT fk_varh_handover
      FOREIGN KEY (handover_location_id) REFERENCES handover_locations (id);
  END IF;

  IF to_regclass('public.vehicles') IS NULL THEN
    RETURN;
  END IF;

  EXECUTE $ins$
    INSERT INTO vehicle_allowed_return_handovers (created_at, updated_at, vehicle_id, handover_location_id, line_order)
    SELECT CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6), v.id, v.default_return_handover_location_id, 0
    FROM vehicles v
    WHERE v.default_return_handover_location_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM vehicle_allowed_return_handovers x WHERE x.vehicle_id = v.id
      )
  $ins$;
END $migration$;
