CREATE TABLE IF NOT EXISTS countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  color_code VARCHAR(16) NOT NULL,
  CONSTRAINT uk_countries_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  name VARCHAR(128) NOT NULL,
  country_id BIGINT NOT NULL,
  CONSTRAINT fk_cities_country FOREIGN KEY (country_id) REFERENCES countries (id)
);

CREATE INDEX IF NOT EXISTS idx_cities_country_id ON cities (country_id);
CREATE INDEX IF NOT EXISTS idx_cities_name ON cities (name);

DO $migration$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'vehicles'
  ) THEN
    ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS city_id BIGINT NULL;
    ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS engine VARCHAR(255) NULL;
    ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS seats INT NULL;
    ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS luggage INT NULL;
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint WHERE conname = 'fk_vehicles_city'
    ) THEN
      ALTER TABLE vehicles
        ADD CONSTRAINT fk_vehicles_city FOREIGN KEY (city_id) REFERENCES cities (id);
    END IF;
    CREATE INDEX IF NOT EXISTS idx_vehicles_city_id ON vehicles (city_id);
  END IF;
END $migration$;
