CREATE TABLE IF NOT EXISTS vehicle_highlights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  vehicle_id BIGINT NOT NULL,
  line_order INT NOT NULL,
  text VARCHAR(500) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_vehicle_highlights_vehicle_id ON vehicle_highlights (vehicle_id);

DO $migration$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'vehicles'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_vehicle_highlights_vehicle'
  ) THEN
    ALTER TABLE vehicle_highlights
      ADD CONSTRAINT fk_vehicle_highlights_vehicle
      FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE;
  END IF;
END $migration$;
