DO $migration$
BEGIN
  IF to_regclass('public.rental_requests') IS NOT NULL THEN
    ALTER TABLE rental_requests ADD COLUMN IF NOT EXISTS rental_nights INT NULL;
    ALTER TABLE rental_requests ADD COLUMN IF NOT EXISTS pricing_total_try DECIMAL(12, 2) NULL;
  END IF;
END $migration$;

CREATE TABLE IF NOT EXISTS rental_request_priced_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  rental_request_id BIGINT NOT NULL,
  line_type VARCHAR(40) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  quantity INT NOT NULL DEFAULT 1,
  unit_amount DECIMAL(12, 2) NOT NULL,
  line_amount DECIMAL(12, 2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'TRY',
  line_order INT NOT NULL DEFAULT 0,
  priced_at timestamptz NULL,
  source_reservation_extra_template_id BIGINT NULL,
  source_vehicle_option_definition_id BIGINT NULL,
  return_handover_location_id BIGINT NULL,
  metadata TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_rrpl_rental_request ON rental_request_priced_lines (rental_request_id);

DO $migration$
BEGIN
  IF to_regclass('public.rental_requests') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rrpl_rental_request') THEN
    ALTER TABLE rental_request_priced_lines
      ADD CONSTRAINT fk_rrpl_rental_request
      FOREIGN KEY (rental_request_id) REFERENCES rental_requests (id) ON DELETE CASCADE;
  END IF;
END $migration$;
