CREATE TABLE IF NOT EXISTS reservation_extra_option_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    code VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(12, 2) NOT NULL,
    icon VARCHAR(512),
    line_order INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_co_driver_details BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_reservation_extra_option_templates_code UNIQUE (code)
);

INSERT INTO reservation_extra_option_templates (
    created_at, updated_at, code, title, description, price, icon, line_order, active, requires_co_driver_details
) VALUES
(
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    'BABY_SEAT',
    'Bebek koltuğu',
    'Çocuk güvenliği için montajlı bebek koltuğu.',
    350.00,
    NULL,
    10,
    TRUE,
    FALSE
),
(
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    'ADDITIONAL_DRIVER',
    'Ek şöför',
    'İkinci sürücü; ehliyet/pasaport numarası ve net görseller zorunludur.',
    350.00,
    NULL,
    20,
    TRUE,
    TRUE
),
(
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    'GREEN_INSURANCE_ME',
    'Yeşil sigorta (Karadağ)',
    'Karadağ sınır geçişleri için yeşil sigorta.',
    700.00,
    NULL,
    30,
    TRUE,
    FALSE
),
(
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    'GREEN_INSURANCE_BALKAN',
    'Yeşil sigorta (AL · XK · ME · MK)',
    'Arnavutluk, Kosova, Karadağ ve Kuzey Makedonya için geçerli yeşil sigorta.',
    1400.00,
    NULL,
    40,
    TRUE,
    FALSE
)
ON CONFLICT (code) DO NOTHING;
