CREATE TABLE IF NOT EXISTS vehicle_body_styles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  label_tr VARCHAR(128) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT uq_vehicle_body_styles_code UNIQUE (code)
);

INSERT INTO vehicle_body_styles (code, label_tr, sort_order) VALUES
  ('SEDAN', 'Sedan', 10),
  ('HATCHBACK', 'Hatchback', 20),
  ('SUV', 'SUV / Jeep', 30),
  ('COUPE', 'Coupe', 40),
  ('ESTATE', 'Station wagon', 50),
  ('VAN', 'Van / Panelvan', 60),
  ('PICKUP', 'Pickup', 70),
  ('MINIBUS', 'Minibüs', 80)
ON CONFLICT (code) DO UPDATE SET
  label_tr = EXCLUDED.label_tr,
  sort_order = EXCLUDED.sort_order;

DO $migration$
BEGIN
  IF to_regclass('public.vehicles') IS NULL THEN
    RETURN;
  END IF;
  ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS transmission_type VARCHAR(32) NULL;
  ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS body_style_code VARCHAR(32) NULL;
END $migration$;
